### ISSUE TITLE
How can I use the client out of process? For instance in a delayed job?

### ISSUE THREAD

**Issue by lostboy** [myitcv/signet-rails#13]
Is it possible, given a user with valid credentials saved in the db to get a Signet::Client object without being in a web request? I would like to run some google drive operations in delayed jobs and still have all of the signet goodness like refreshing of tokens etc.

**Comment by myitcv** [comment]
Yes, you would need to do this by first getting hold of a refresh token (Google describe this as offline access). The refresh token gives you the ability to, offline from the user (i.e. outside of a web request), create access tokens which can then be used to perform API requests that the user previously authorised. 

See https://developers.google.com/accounts/docs/OAuth2WebServer for more details

As a post script, I will apologise in advance - this project is no longer being maintained (and probably well out of date as a result)

**Comment by lostboy** [comment]
Thanks but your answer is just how to do it from a high level, I understand the concepts but i wish to understand how signet-rails could do this without the middleware handler that sets env variables. Not to worry if its not maintained any more though. Thanks.
